name: HelloWorld

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install npm packages
        run: npm ci
      - name: Hello World
        uses: ./.github/workflows/actions/hellooworld
        with:
          example-param: Hello World
